import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [news, setNews] = useState("");

  return (
    <>
      <Head>
        <title>Financial sentiment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="mx-20 my-40 flex flex-col justify-center items-center">
        <h1 className="text-4xl font-bold mb-2">
          Financial Sentiment Analyser
        </h1>
        <p className="text-xl font-light mb-5 flex flex-wrap items-center justify-center">
          Enter financial news and let us predict the sentiment of your data.
        </p>
        <textarea
          className="textarea textarea-bordered w-[500px] mt-5"
          rows={5}
          placeholder="Your financial news here"
          onChange={(e) => {
            setNews(e.target.value);
          }}
        ></textarea>
        <span className="flex flex-row space-x-3 mt-4 items-center">
          <button className="btn btn-info">
            Predict using Naive bayes model
          </button>
          <p>or</p>
          <button className="btn btn-success">Predict using BARF model</button>
        </span>
      </main>
    </>
  );
}
